/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package image;

import java.awt.Image;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author rohan jack
 */
public class imageview extends javax.swing.JFrame implements Serializable{
photo objnew;
int ind=-1;
 public static void serialize(ArrayList<String> album)
	{
		try{					   
			FileOutputStream file_out = new FileOutputStream("img.txt");
			ObjectOutputStream obj_out = new ObjectOutputStream(file_out);   
			obj_out.writeObject(album);
			
			obj_out.close();		
			file_out.close();
	    }
		catch(Exception e)
		{
			System.out.println("ERROR : Something went wrong Could not save data !!!");
			e.printStackTrace();
		}
	}
public static ArrayList<String> deserialize()
	{
		ArrayList<String> arrayc = null;
		try{
		FileInputStream inputFileStream = new FileInputStream("img.txt");
	      ObjectInputStream objectInputStream = new ObjectInputStream(inputFileStream);
	      arrayc = (ArrayList<String>)objectInputStream.readObject();
	      objectInputStream.close();
	      inputFileStream.close();	      
		}catch(Exception e){}
		return arrayc;
	}
  public ImageIcon ResizeImage(String ImagePath,JLabel label)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    public imageview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp1 = new javax.swing.ButtonGroup();
        limage = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        rb9 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        pre = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rb1.setVisible(false);
        grp1.add(rb1);
        rb1.setText("jRadioButton1");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        rb2.setVisible(false);
        grp1.add(rb2);
        rb2.setText("jRadioButton2");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        rb3.setVisible(false);
        grp1.add(rb3);
        rb3.setText("jRadioButton3");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        rb4.setVisible(false);
        grp1.add(rb4);
        rb4.setText("jRadioButton4");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });

        rb5.setVisible(false);
        grp1.add(rb5);
        rb5.setText("jRadioButton5");
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });

        rb6.setVisible(false);
        grp1.add(rb6);
        rb6.setText("jRadioButton6");
        rb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6ActionPerformed(evt);
            }
        });

        rb7.setVisible(false);
        grp1.add(rb7);
        rb7.setText("jRadioButton7");
        rb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb7ActionPerformed(evt);
            }
        });

        rb8.setVisible(false);
        grp1.add(rb8);
        rb8.setText("jRadioButton8");
        rb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb8ActionPerformed(evt);
            }
        });

        rb9.setVisible(false);
        grp1.add(rb9);
        rb9.setText("jRadioButton9");
        rb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb9ActionPerformed(evt);
            }
        });

        rb10.setVisible(false);
        grp1.add(rb10);
        rb10.setText("jRadioButton10");
        rb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb10ActionPerformed(evt);
            }
        });

        pre.setText("previous");
        pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preActionPerformed(evt);
            }
        });

        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        jButton1.setText("Delete Selected");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Display Title");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("clear");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rb2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rb1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(pre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(next)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(limage, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb10)
                        .addGap(51, 51, 51)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(limage, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next)
                    .addComponent(pre))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       limage.setIcon(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
int i=0;

if(objnew==null)
{
    objnew=new photo();
}
objnew.album=deserialize();
  
if(objnew.album.size()>=2)
{rb1.setVisible(true);
        rb1.setText(objnew.album.get(i));}
if(objnew.album.size()>=5)
{ rb2.setVisible(true);
            rb2.setText(objnew.album.get(i+3));
}
if(objnew.album.size()>=8)
{rb3.setVisible(true);
                rb3.setText(objnew.album.get(i+6));
}
if(objnew.album.size()>=11)
    {rb4.setVisible(true);
                    rb4.setText(objnew.album.get(i+9));
    }
if(objnew.album.size()>=14)
{rb5.setVisible(true);
                        rb5.setText(objnew.album.get(i+12));
}
if(objnew.album.size()>=17)
{rb6.setVisible(true);
                            rb6.setText(objnew.album.get(i+15));
}
if(objnew.album.size()>=20)
{rb7.setVisible(true);
                                rb7.setText(objnew.album.get(i+18));
}
if(objnew.album.size()>=23)
{rb8.setVisible(true);
                                    rb8.setText(objnew.album.get(i+21));
}
if(objnew.album.size()>=26)
{rb9.setVisible(true);
                                        rb9.setText(objnew.album.get(i+24));
}
if(objnew.album.size()>=29)
{rb10.setVisible(true);

                                            rb10.setText(objnew.album.get(i+27));
}
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
if(objnew.album.size()>=2)
{
    limage.setIcon(ResizeImage(objnew.album.get(2),limage));
}
       
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
if(objnew.album.size()>=5)
{ 
    limage.setIcon(ResizeImage(objnew.album.get(5),limage)); 
}// TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
if(objnew.album.size()>=8)
{
        limage.setIcon(ResizeImage(objnew.album.get(8),limage));  
}// TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
if(objnew.album.size()>=11)
    {
        limage.setIcon(ResizeImage(objnew.album.get(11),limage));
    }        // TODO add your handling code here:
    }//GEN-LAST:event_rb4ActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
if(objnew.album.size()>=14)
{
    limage.setIcon(ResizeImage(objnew.album.get(14),limage));
}        // TODO add your handling code here:
    }//GEN-LAST:event_rb5ActionPerformed

    private void rb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6ActionPerformed
if(objnew.album.size()>=17)
{
    limage.setIcon(ResizeImage(objnew.album.get(17),limage));
}        // TODO add your handling code here:
    }//GEN-LAST:event_rb6ActionPerformed

    private void rb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb7ActionPerformed
if(objnew.album.size()>=20)
{
    limage.setIcon(ResizeImage(objnew.album.get(20),limage));
}        // TODO add your handling code here:
    }//GEN-LAST:event_rb7ActionPerformed

    private void rb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb8ActionPerformed
if(objnew.album.size()>=23)
{
    limage.setIcon(ResizeImage(objnew.album.get(23),limage));
}        // TODO add your handling code here:
    }//GEN-LAST:event_rb8ActionPerformed

    private void rb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb9ActionPerformed
if(objnew.album.size()>=26)
{
    limage.setIcon(ResizeImage(objnew.album.get(26),limage));
}        // TODO add your handling code here:
    }//GEN-LAST:event_rb9ActionPerformed

    private void rb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb10ActionPerformed
if(objnew.album.size()>=29)
{
    limage.setIcon(ResizeImage(objnew.album.get(29),limage));
}        // TODO add your handling code here:
    }//GEN-LAST:event_rb10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
 ind=ind+3;
 if(ind>objnew.album.size()-1)
 { ind=2;
 }     

 limage.setIcon(ResizeImage(objnew.album.get(ind),limage));  
    }//GEN-LAST:event_nextActionPerformed

    private void preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preActionPerformed
    ind=ind-3;
    if(ind<2)
    {  ind=objnew.album.size()-1;
    
    }
        limage.setIcon(ResizeImage(objnew.album.get(ind),limage));    
    }//GEN-LAST:event_preActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int dialogButton = JOptionPane.YES_NO_OPTION;
            JOptionPane.showConfirmDialog (null, "Are you sure?","WARNING", dialogButton);
            if(dialogButton == JOptionPane.YES_OPTION)
            {
                if(rb1.isSelected())
            { objnew.album.remove(0);
            objnew.album.remove(1);
            objnew.album.remove(2);
            }
                  if(rb2.isSelected())
            { objnew.album.remove(3);
            objnew.album.remove(4);
            objnew.album.remove(5);
            }
                    if(rb3.isSelected())
            { objnew.album.remove(6);
            objnew.album.remove(7);
            objnew.album.remove(8);
            }
                      if(rb4.isSelected())
            { objnew.album.remove(9);
            objnew.album.remove(10);
            objnew.album.remove(11);
            }
                        if(rb5.isSelected())
            { objnew.album.remove(12);
            objnew.album.remove(13);
            objnew.album.remove(14);
            }
                          if(rb6.isSelected())
            { objnew.album.remove(15);
            objnew.album.remove(16);
            objnew.album.remove(17);
            }
                                  if(rb7.isSelected())
            { objnew.album.remove(18);
            objnew.album.remove(19);
            objnew.album.remove(20);
            }
                                          if(rb8.isSelected())
            { objnew.album.remove(21);
            objnew.album.remove(22);
            objnew.album.remove(23);
            }
                                                  if(rb9.isSelected())
            { objnew.album.remove(24);
            objnew.album.remove(25);
            objnew.album.remove(26);
            }
                                                          if(rb10.isSelected())
            { objnew.album.remove(27);
            objnew.album.remove(28);
            objnew.album.remove(29);
            }
             serialize(objnew.album);
             JOptionPane.showMessageDialog(null,"Succesfully deleted");
            }
            if(dialogButton == JOptionPane.NO_OPTION) 
            { remove(dialogButton);}
                   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int i=0;

if(objnew==null)
{
    objnew=new photo();
}
objnew.album=deserialize();
  
if(objnew.album.size()>=2)
{rb1.setVisible(true);
        rb1.setText(objnew.album.get(i));}
if(objnew.album.size()>=5)
{ rb2.setVisible(true);
            rb2.setText(objnew.album.get(i+3));
}
if(objnew.album.size()>=8)
{rb3.setVisible(true);
                rb3.setText(objnew.album.get(i+6));
}
if(objnew.album.size()>=11)
    {rb4.setVisible(true);
                    rb4.setText(objnew.album.get(i+9));
    }
if(objnew.album.size()>=14)
{rb5.setVisible(true);
                        rb5.setText(objnew.album.get(i+12));
}
if(objnew.album.size()>=17)
{rb6.setVisible(true);
                            rb6.setText(objnew.album.get(i+15));
}
if(objnew.album.size()>=20)
{rb7.setVisible(true);
                                rb7.setText(objnew.album.get(i+18));
}
if(objnew.album.size()>=23)
{rb8.setVisible(true);
                                    rb8.setText(objnew.album.get(i+21));
}
if(objnew.album.size()>=26)
{rb9.setVisible(true);
                                        rb9.setText(objnew.album.get(i+24));
}
if(objnew.album.size()>=29)
{rb10.setVisible(true);

                                            rb10.setText(objnew.album.get(i+27));
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(imageview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(imageview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(imageview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(imageview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new imageview().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grp1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel limage;
    private javax.swing.JButton next;
    private javax.swing.JButton pre;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    // End of variables declaration//GEN-END:variables
}
